# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cwRqv0dyBoK00w9_u_6X83z2FFwiRmf
"""

import numpy as np

def expected_shortfall(losses, alpha=None, VaR=None):
    if VaR is None:

        VaR = np.percentile(losses, 100 * alpha)

    es_value = np.mean(losses[losses > VaR])
    return es_value

np.random.seed(42)
u = np.random.uniform(0, 100, 100000)