# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cwRqv0dyBoK00w9_u_6X83z2FFwiRmf
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

def percent_var(r, confidence):

    out = np.percentile(r, (1 - confidence) * 100)
    return abs(out)
returns = np.random.normal(0, 1, 10000)

print("97.72 percentile of returns:", np.percentile(returns, 97.72))

r = np.random.normal(0.05, 0.03, 100000)
probability_2SD = norm.cdf(2)

my_confidence = probability_2SD
my_percent_var = percent_var(r, my_confidence)

print("VaR at confidence level {:.2f}: {:.4f}".format(my_confidence, my_percent_var))
plt.hist(r, bins=50, alpha=0.75, color='blue', edgecolor='black')
plt.axvline(-my_percent_var, color='red', linestyle='dashed', linewidth=2)
plt.title("Histogram of Stock Returns with Value at Risk (VaR)")
plt.xlabel("Returns")
plt.ylabel("Frequency")
plt.show()